### ISSUE TITLE
What is the special meaning of this algorithm：lt_deBruijn_to_idx[((x&-x)*deBruijn64)>>58]

### ISSUE THREAD

**Issue by Wenmj201582** [ekg/seqwish#103]
Seqwish-v0.7.5 is ok when compiled with gcc, but **an error occurs when compiled with the HUAWEI BiSheng Compiler 2.1.0. B010**。
![image](https://user-images.githubusercontent.com/77086644/195245248-3b895091-e63e-4e84-ac37-d073bb7ece73.png)

After troubleshooting, the error is caused by the algorithm in line 432 of the **deps/sdsl lite/include/sdsl/bits. hpp** file,
![image](https://user-images.githubusercontent.com/77086644/195245102-b16807a7-e3f1-4300-8734-35c906a09a86.png)

1、What is the special significance of this algorithm? **lt_deBruijn_to_idx[((x&-x)*deBruijn64)>>58]**, what does 58 bit shift represent;

2、If I use the Bi Sheng compiler, how can I solve this problem?

**Comment by AndreaGuarracino** [comment]
Why are you not using `gcc` or the standard `clang`?

Regarding the error, I was going to suggest asking directly on the sdsl-lite repository, but I've seen you are already there (https://github.com/simongog/sdsl-lite/issues/452).

I was able to build `seqwish` with the standard `clang`. I've just pushed a few instructions in the README about how to do it: https://github.com/ekg/seqwish#clang. Since you are using some vendor-modified clang, please consider reporting this issue to the compiler vendor.
